name: Release

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Release
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        MEMBERPRESS_LICENSE_KEY: ${{ secrets.MEMBERPRESS_LICENSE_KEY }}
        MEMBERPRESS_LICENSE_DOMAIN: ${{ secrets.MEMBERPRESS_LICENSE_DOMAIN }}
      run: php .github/scripts/release.php
